name: "Test"
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build
        working-directory: front
        run: |
          cmake ./
          make

      - name: Unit tests
        working-directory: front
        run: build/test
        
      - name: GLL4Graph
        working-directory: third-party
	run: | 
           git clone https://github.com/JetBrains-Research/GLL4Graph.git
	   cd GLL4Graph
	   mkdir results
	   export JAVA_HOME='/usr/lib/jvm/jdk-15.0.2'
